// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz_9810YoyL36AI46BlMb4Qc-7pRqns4g',
    appId: '1:174733700303:web:47299d046c70b0b6a49bba',
    messagingSenderId: '174733700303',
    projectId: 'authorizationexample-a79fa',
    authDomain: 'authorizationexample-a79fa.firebaseapp.com',
    storageBucket: 'authorizationexample-a79fa.firebasestorage.app',
    measurementId: 'G-8CQ6ZJPT7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1aywlRmaDtuRW2WWs3YT0aKVPsZL6fSM',
    appId: '1:174733700303:android:5e7e2c92275c86a8a49bba',
    messagingSenderId: '174733700303',
    projectId: 'authorizationexample-a79fa',
    storageBucket: 'authorizationexample-a79fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDifICQL6GkXvUacGA8XgsivJpZnwX_eos',
    appId: '1:174733700303:ios:1fdff6a90f369455a49bba',
    messagingSenderId: '174733700303',
    projectId: 'authorizationexample-a79fa',
    storageBucket: 'authorizationexample-a79fa.firebasestorage.app',
    iosClientId: '174733700303-881om8iq4jsscgv4kpoebt89iv4etnrl.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDifICQL6GkXvUacGA8XgsivJpZnwX_eos',
    appId: '1:174733700303:ios:1fdff6a90f369455a49bba',
    messagingSenderId: '174733700303',
    projectId: 'authorizationexample-a79fa',
    storageBucket: 'authorizationexample-a79fa.firebasestorage.app',
    iosClientId: '174733700303-881om8iq4jsscgv4kpoebt89iv4etnrl.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz_9810YoyL36AI46BlMb4Qc-7pRqns4g',
    appId: '1:174733700303:web:effab13f5e5fa96ca49bba',
    messagingSenderId: '174733700303',
    projectId: 'authorizationexample-a79fa',
    authDomain: 'authorizationexample-a79fa.firebaseapp.com',
    storageBucket: 'authorizationexample-a79fa.firebasestorage.app',
    measurementId: 'G-X01FSVBCH3',
  );
}
